### ISSUE TITLE
Não está funcionando 

### ISSUE THREAD

**Issue by luquinhaspmw** [emanuellresende/whatsapp-sticker-bot#1]
...

**Comment by emanuellresende** [comment]
qual erro meu amigo?

**Comment by emanuellresende** [comment]
voce criou o arquivo .env e colocou seu numero?

**Comment by luquinhaspmw** [comment]
> voce criou o arquivo .env e colocou seu numero?
> 

não, o arquivo só precisa conter o número? 
qual o formato do número?

**Comment by emanuellresende** [comment]
crie o arquivo .env, adicione a variavel WHATSAPP_NUMBER = "seunumero"
Seu numero nao pode conter o numero 9 extra, ou seja. exemplo: WHATSAPP_NUMBER = "3597144664"

**Comment by luquinhaspmw** [comment]
> crie o arquivo .env, adicione a variavel WHATSAPP_NUMBER = "seunumero"
> Seu numero nao pode conter o numero 9 extra, ou seja. exemplo: WHATSAPP_NUMBER = "3597144664"

dps eu posso rodar o node index.js que vai gerar o qr code né?

**Comment by emanuellresende** [comment]
exato

**Comment by emanuellresende** [comment]
conseguiu?
